/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  // tutorialSidebar: [
  //   'intro',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],

  frontIndex: [
    {
      type: 'category',
      label: '目录',
      link: {
        type: 'generated-index',
        title: '目录集合',
        slug: '/front',
        description: '介绍'
      },
      items: [
        {
          type: 'category',
          label: 'Docusaurus',
          link: {
            type: 'generated-index',
            title: 'Docusaurus',
            description: '🧐 Docusaurus 是一款静态站点生成器。 可以搭建带有快速客户端导航的单页应用，充分利用了 React，让你的网站具有交互能力。 它提供了开箱即用的文档功能，不过也可用于搭建各种网站（个人网站、产品、博客、营销主页，等等）。',
            slug: '/front/Docusaurus',
          },
          items: [
            'front/Docusaurus/introduction',
            {
              type: 'category',
              label: 'MarkDown特性',
              link: {
                type: 'generated-index',
                title: 'Docusaurus',
                description: '🧐 Docusaurus 是一款静态站点生成器。 可以搭建带有快速客户端导航的单页应用，充分利用了 React，让你的网站具有交互能力。 它提供了开箱即用的文档功能，不过也可用于搭建各种网站（个人网站、产品、博客、营销主页，等等）。',
                slug: '/front/Docusaurus/markdown',
                image: '/img/architecture.png'
              },
              items:[
                'front/Docusaurus/markdown/MarkDownFeatures',
                'front/Docusaurus/markdown/MarkDownTab',
                'front/Docusaurus/markdown/MarkDownCodeBlock',
                'front/Docusaurus/markdown/MarkDownPlacard',
                'front/Docusaurus/markdown/MarkDownTitleAndDir',
                'front/Docusaurus/markdown/MarkDownEmoji',
                'front/Docusaurus/markdown/MarkDownResource',
                'front/Docusaurus/markdown/MarkDownDiagrams',
                
              ]
            }
            
          ]
        }
      ]
    }
  ],
};

module.exports = sidebars;
